---
language: node_js
node_js:
  - 'node'
  - '8.0.0'
  - '10'
  - '12'

dist: trusty
sudo: false
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - mysql -e "CREATE USER 'testuser'@'%';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%'"
